config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invites
  get 'home/index'
  root 'invites#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :user
  validates_uniqueness_of :user_id, :message => "User can only have one Invite"
  validates :user_id, presence: true

  has_attached_file :header_image, styles: { cover: "1440x400>"}, default_url: "/images/:style/default_header_image.png"
  has_attached_file :bride_image, styles: { thumb: "200x200>"}, default_url: "/images/:style/default_header_image.png"
  has_attached_file :groom_image, styles: { thumb: "200x200>"}, default_url: "/images/:style/default_header_image.png"
  validates_attachment_content_type :header_image, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :bride_image, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :groom_image, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_one :invite, :dependent => :destroy
  before_create :create_invite

  def create_invite
    invite = build_invite(:header_title => "Bride & Groom", :wedding_date => "17 August 2017",)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  before_action :set_invite, only: [:show, :edit, :update]


  def index
    @invites = Invite.all
  end

  def show
  end

  def new
    @invite = current_user.build_invite
  end

  def create
    @invite = current_user.build_invite(invite_params)

    respond_to do |format|
      if @invite.save
        format.html { redirect_to @invite, notice: 'Invite was successfully created.' }
        format.json { render :show, status: :created, location: @invite }
      else
        format.html { render :new }
        format.json { render json: @pinvite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @invite.update(invite_params)
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { render :show, status: :ok, location: @invite }
      else
        format.html { render :edit }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_params
      params.require(:invite).permit(:background_color, :font_color,
      :font_family, :header_title, :header_image, :wedding_date, :bride_image,
      :bride_name, :bride_description, :groom_image, :groom_name, :groom_description,
      :about_title, :about_description, :map_coordinates, :map_description)
    end

    # Confirms the correct user.
    def correct_user
      @invite = Invite.find(params[:id])
      flash[:notice] = 'Dont have permission to modify this post'
      redirect_to(root_path) unless current_user.id == @invite.user_id
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/home/index.html.erb
<h1>Smitten</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/invites/_form.html.erb
<%= form_for(invite) do |f| %>
  <% if invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% invite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Submit", :type => :image, :src => image_path("save.png") %>
  </div>

  <div class="field">
    <h3 class="section-title">Theme</h3>
    <%= f.label :background_color %>
    <%= f.text_field :background_color, class: 'colorpicker' %>

    <%= f.label :font_color %>
    <%= f.text_field :font_color, class: 'colorpicker'%>

    <%= f.label :font_family %>
    <%= f.select :font_family, ['Helvetica', 'Didot','Roboto','Lato','Kepler-Std','Raleway']%>

    <hr>

    <h3 class="section-title">Header</h3>

    <%= f.label :header_title %>
    <%= f.text_field :header_title %>

    <%= f.label :header_image %>
    <%= f.file_field :header_image %>

    <%= f.label :wedding_date %>
    <%= f.text_field :wedding_date %>

    <hr>

    <h3 class="section-title">Bride &amp Groom</h3>

    <%= f.label :bride_image %>
    <%= f.file_field :bride_image %>

    <%= f.label :bride_name %>
    <%= f.text_field :bride_name %>

    <%= f.label :bride_description %>
    <%= f.text_area :bride_description %>

    <hr>

    <%= f.label :groom_image %>
    <%= f.file_field :groom_image %>

    <%= f.label :groom_name %>
    <%= f.text_field :groom_name %>

    <%= f.label :groom_description %>
    <%= f.text_area :groom_description %>

    <hr>

    <%= f.label :about_title %>
    <%= f.text_field :about_title %>

    <%= f.label :about_description %>
    <%= f.text_area :about_description %>

    <hr>

    <%= f.label :map_coordinates %>
    <%= f.text_field :map_coordinates %>

    <%= f.label :map_description %>
    <%= f.text_field :map_description %>
  </div>

<% end %>

app/views/invites/edit.html.erb
<div>

<div style="width:25%; height: 100%; float:left; background:#F6F6F6; padding:10px">
  <%= render 'form', invite: @invite %>
</div>

<div style="width:75%; float:left; padding:20px; background:#EDEDED;">
  <div style="background:<%= @invite.font_color %>">COLOR</div>
  <div style="background: #FFF;">
    <div style="width:100%; height:50vh; background-size:cover; background-position:center; background-image: url(<%= @invite.header_image.url(:cover) %>);">
    <h1 style="color: <%= @invite.font_color %>; text-align:center; padding-top:20vh; font-family:<%= @invite.font_family %>;"><%= @invite.header_title %></h1>
    <h4 style="color: <%= @invite.font_color %>; text-align:center;">IS GETTING MARRIED <%= @invite.wedding_date %></h4>
    </div>

    <div style="width:100%; height:50vh;">
    <h2 style="text-align:center; padding-top:10vh; font-family:<%= @invite.font_family %>;"><%= @invite.about_title; %></h2>
    <p style="text-align:center;">
      <%= @invite.about_description; %>
    </p>
    </div>
  </div>
</div>

</div>

app/views/invites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invites</h1>

<table>
  <thead>
    <tr>
      <th>Header title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invites.each do |invite| %>
      <tr>
        <td><%= invite.header_title %></td>
        <td><%= link_to 'Show', invite %></td>
        <td><%= link_to 'Edit', edit_invite_path(invite) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invites/new.html.erb
<h1>New Invite</h1>

<%= render 'form', invite: @invite %>

<%= link_to 'Back', invites_path %>

app/views/invites/show.html.erb
<div style="width:100%; height:50vh; background-size:cover; background-position:center; background-image: url(<%= @invite.header_image.url(:cover) %>);">
<h1 style="color:white; text-align:center; padding-top:20vh; font-family:<%= @invite.font_family %>;"><%= @invite.header_title %></h1>
<h4 style="color:white; text-align:center;">IS GETTING MARRIED <%= @invite.wedding_date %></h4>
</div>

<div style="width:100%; height:50vh;">
<h2 style="text-align:center; padding-top:10vh; font-family:<%= @invite.font_family %>;">STORY</h2>
<p style="text-align:center;">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam scelerisque cursus fringilla. Morbi ullamcorper velit id erat molestie, eget ultrices enim luctus. Phasellus dolor elit, condimentum sed mauris in, sollicitudin mollis tellus. Nullam vulputate quis velit et posuere. Ut a lacus sollicitudin lorem mollis interdum et non felis.
</p>
</div>


<p>
  <strong>Details:</strong> <br>
  <%= @invite.background_color %> <br>
  <%= @invite.font_color %> <br>
  <%= @invite.font_family %> <br>

  <%= @invite.header_title %> <br>
  <%= image_tag @invite.header_image.url(:cover) %> <br>
  <%= @invite.wedding_date %> <br>

  <%= image_tag @invite.bride_image.url(:thumb) %> <br>
  <%= @invite.bride_name %> <br>
  <%= @invite.bride_description %> <br>

  <%= image_tag @invite.groom_image.url(:thumb) %> <br>
  <%= @invite.groom_name %> <br>
  <%= @invite.groom_description %> <br>

  <%= @invite.about_title %> <br>
  <%= @invite.about_description %> <br>

  <%= @invite.map_coordinates %> <br>
  <%= @invite.map_description %> <br>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smitten</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="navagation">
  <% if user_signed_in? %>
    <%= link_to "View Template", current_user.invite %>
    <%= link_to "Edit Template", edit_invite_path(current_user.invite) %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    <p id="notice"><%= notice %></p>
  <% else %>
    <%= link_to('Login', new_user_session_path)  %>
  <% end %>
  </div>
  <br><br>

    <%= yield %>
  </body>
</html>